feed/urls.py
from django.urls import path

from . import views

app_name = "feed"

urlpatterns = [
    path("", views.HomePage.as_view(), name="index"),
    path("<int:pk>/", views.PostDetailView.as_view(), name='detail'),
    path("new/", views.CreateNewPost.as_view(), name="new_post"),
]

profiles/urls.py
from django.urls import path

from . import views

app_name = "profiles"

urlpatterns =[
    path("<str:username>/", views.ProfileDetailView.as_view(), name="detail"),
    path("<str:username>/follow/", views.FollowView.as_view(), name="follow"),
]

til/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path
from feed import urls as feed_urls
from profiles import urls as profiles_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include(feed_urls, namespace="feed")),
    path("profile/", include(profiles_urls, namespace="profiles")),
    path("", include("allauth.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feed/models.py
from django.contrib.auth.models import User
from django.db import models

class Post(models.Model):
    text = models.CharField(max_length=240)
    date = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(
        User, 
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return(self.text)

followers/models.py
from django.db import models
from django.contrib.auth.models import User

class Follower(models.Model):
    followed_by = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='followed_by'
    )
    following = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )
    
    def __str__(self):
        return f"{self.followed_by.id} is following {self.following.id}"
    
    class Meta:
        unique_together = ('followed_by', 'following',)

profiles/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from sorl.thumbnail import ImageField

class Profile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name="profile"
    )
    
    image = ImageField(upload_to='profiles')
    
    def __str__(self):
        return self.user.username
    
@receiver(post_save, sender=User)    
def create_user_profile(sender, instance,created, **kwargs):
    """Create an new Profile() when a new user is created"""
    if created:
        Profile.objects.create(user=instance)

feed/views.py
from django.views.generic import TemplateView, DetailView 
from django.views.generic.edit import CreateView 
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render

from followers.models import Follower

from .models import Post

class HomePage(TemplateView):
    http_method_names = ["get"]
    template_name = "feed\homepage.html"
    
    def dispatch(self, request, *args,**kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)
    
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        if self.request.user.is_authenticated:
            following = list(
                Follower.objects.filter(followed_by=self.request.user).values_list('following', flat=True)
            )
            if not following:
                #show the default 30
                posts = Post.objects.all().order_by('-id')[0:30]
            else:
                posts = Post.objects.filter(author__in=following).order_by('-id')[0:60]
        else:
            posts = Post.objects.all().order_by('-id')[0:30]
        context['posts'] = posts
        return context
    
class PostDetailView(DetailView):
    http_method_names = ["get"]
    template_name = "feed/detail.html"
    model = Post
    context_object_name = "post"
    
class CreateNewPost(LoginRequiredMixin, CreateView):
    template_name = "feed/create.html"
    model = Post
    fields = ['text']
    success_url ="/"
    
    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request,*args, **kwargs)
    
    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.author = self.request.user
        obj.save()
        return super().form_valid(form)
    
    def post(self, request, *args, **kwargs):
        post= Post.objects.create(
            text=request.POST.get("text"),
            author=request.user,
        )
        return render(
            request,
            "includes/post.html",
            {
                "post":post,
                "show_detail_link":True,
            },
            content_type = "application/html"
        )

followers/views.py
from django.shortcuts import render

# Create your views here.

profiles/views.py
from django.contrib.auth.models import User
from django.views.generic import DetailView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, HttpResponseBadRequest

from feed.models import Post
from followers.models import Follower


class ProfileDetailView(DetailView):
    http_method_names = ["get"]
    template_name = "profiles/detail.html"
    model = User
    context_object_name = "user"
    slug_field = "username"
    slug_url_kwarg = "username"

    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        user = self.get_object()
        context = super().get_context_data(**kwargs)
        context['total_posts'] = Post.objects.filter(author=user).count()
        # context['total_followers'] = ...
        if self.request.user.is_authenticated:
            context['you_follow'] = Follower.objects.filter(following=user, followed_by=self.request.user).exists()
        return context


class FollowView(LoginRequiredMixin, View):
    http_method_names = ["post"]

    def post(self, request, *args, **kwargs):
        data = request.POST.dict()

        if "action" not in data or "username" not in data:
            return HttpResponseBadRequest("Missing data")

        try:
            other_user = User.objects.get(username=data['username'])
        except User.DoesNotExist:
            return HttpResponseBadRequest("Missing user")

        if data['action'] == "follow":
            # Follow
            follower, created = Follower.objects.get_or_create(
                followed_by=request.user,
                following=other_user
            )
        else:
            # Unfollow
            try:
                follower = Follower.objects.get(
                    followed_by=request.user,
                    following=other_user,
                )
            except Follower.DoesNotExist:
                follower = None

            if follower:
                follower.delete()

        return JsonResponse({
            'success': True,
            'wording': "Unfollow" if data['action'] == "follow" else "Follow"
        })

feed/templates/feed/create.html
{% extends 'base.html' %}
{% block title %}Create A New Post
{% endblock %}
{% block body %}
    <form action="." method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="my-3">
            <button class="bg-white text-gray-800 font-bold rounded border-b-2 border-green-500 hover:border-green-600 hover:bg-green-500 hover:text-white shadow-md py-2 px-6 inline-flex items-center" type="submit">
              <span class="mr-2">Create post</span>
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                <path fill="currentcolor" d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z"></path>
              </svg>
            </button>
          </div>
    </form>
{% endblock %}

feed/templates/feed/detail.html
{% extends "base.html"%}

{% block title %}{{post.text}} by {{ post.author.username}}{% endblock %}

{% block body %}
    <!-- component from post.html -->
    {% include "includes/post.html" with post=post %}
{% endblock %}

feed/templates/feed/homepage.html
{% extends 'base.html'%}
{% block title %}Homepage{% endblock %}
{% block body %}
    <div class="posts-container">
        {% for post in posts %}
            <!-- component from post.html-->
            {% include "includes/post.html" with post=post show_detail_link=True %}
        {% endfor %}
    </div>
{% endblock %}

profiles/templates/profiles/detail.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}{{ user.username }}
{% endblock %}
{% block body %}
<!-- component -->
<div class="rounded-3xl overflow-hidden shadow-xl max-w-xs my-3 bg-white-500">
    <img src="https://i.imgur.com/dYcYQ7E.png" class="w-full" />
  <div class="flex justify-center -mt-8">
    {% thumbnail user.profile.image "150x150" crop="center" as im %}
      <img src="{{ im.url }}" class="rounded-full border-solid border-gray border-2 -mt-3" data-aos="fade-down"
      data-aos-easing="linear"
      data-aos-duration="1500">
    {% endthumbnail %}		
  </div>
  <div class="text-center px-3 pb-6 pt-2">
      <h3 class="text-gray text-sm bold font-sans">{{ user.username }}</h3>
  </div>
{% if request.user.is_authenticated %}
  {% if request.user != user %}
    <div class="my-3 text-center">
        <button class="bg-white text-gray-800 font-bold rounded border-b-2 border-green-500 hover:border-green-600 hover:bg-green-500 hover:text-white shadow-md py-2 px-6 inline-flex items-center js-follow" data-username="{{ user.username }}" data-action="{% if you_follow %}un{% endif %}" data-url="{% url 'profiles:follow' user.username %}"  type="button">
            <span class="mr-2 js-follow-text">
                {% if you_follow %}
                    Unfollow
                {% else %}
                    Follow
                {% endif %}</span>
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                    <path fill="currentcolor" d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z"></path>
                </svg>
        </button>
    </div>
  {% endif %}
{% else %}
    <div class="mt-3 text-sm text-center">
        Login to follow user
    </div>
{% endif %}
    <div class="flex justify-center pb-3 text-gray">
    <div class="text-center mr-3 border-r pr-3">
      <h2>{{ total_posts }}</h2>
      <span>Post</span>
    </div>
    <div class="text-center">
        <h2>{{ total_followers }}</h2>
      <span>Followers</span>
    </div>
    </div>
</div>

{% endblock %}

til/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}Default Title in here{% endblock %}
    </title>
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css" />
</head>
<body>
<!-- component from "https://tailwindcomponents.com/component/sidebar-navigation" -->

<div class="min-h-screen flex flex-row bg-gray-100">
  <div class="flex flex-col w-56 bg-white rounded-r-3xl overflow-hidden">
    <div class="flex items-center justify-center h-20 shadow-md">
      <h1 class="text-3xl uppercase text-red-500">Til</h1>
    </div>
    <ul class="flex flex-col py-4">
      <li>
        <a href="/" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
          <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i class='bx bxs-home bx-tada' style='color:#f82206' ></i></span>
          <span class="text-sm font-medium">Home</span>
        </a>
      </li>
      {% if request.user.is_authenticated %}
      <li>
        <a href="{% url 'feed:new_post'%}" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800 js-toggle-modal">
          <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i class='bx bxs-layer-plus bx-tada' style='color:#06f850' ></i></span>
          <span class="text-sm font-medium">New post</span>
        </a>
      </li>
      {% else %}

      {% endif %}
      {% if request.user.is_authenticated %}
      <li>
        <a href="{% url 'account_logout'%}" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
          <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i class='bx bxs-log-out bx-tada' style='color:#f8ab06' ></i></span>
          <span class="text-sm font-medium">Logout</span>
        </a>
      </li>
      {% else %}
      <li>
      <a href="{% url 'account_login'%}" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
        <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i class='bx bxs-log-in bx-tada' style='color:#06f842' ></i></span>
        <span class="text-sm font-medium">Login</span>
      </a>
    </li>
    {% endif %}
    </ul>
  </div>
  <div class="p-16">
      {% block body %}
      {% block content %}{% endblock %}
      {% endblock %}
  </div>
</div>
<div>

{% if request.user.is_authenticated %}
  <!-- component -->
  <div class="flex items-center justify-center fixed left-0 bottom-0 w-full h-full bg-gray-800 bg-opacity-75 js-modal hidden">
    <div class="bg-white rounded-lg w-1/2">
      <div class="flex flex-col items-start p-4">
        <div class="flex items-center w-full">
          <div class="text-gray-900 font-medium text-lg">New Post</div>
      
          <svg class="ml-auto fill-current text-gray-700 w-6 h-6 cursor-pointer js-toggle-modal" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18 18">
            <path d="M14.53 4.53l-1.06-1.06L9 7.94 4.53 3.47 3.47 4.53 7.94 9l-4.47 4.47 1.06 1.06L9 10.06l4.47 4.47 1.06-1.06L10.06 9z"/>
            </svg>
            </div>
            <hr>
            <div class="w-full">
              <textarea class="border-2 border-blue-500 my-4 w-full js-post-text" placeholder="Enter your post" maxlength="240" rows="3" data-post-url="{% url 'feed:new_post'%}"></textarea>
            </div>
            <hr>
            <div class="ml-auto">
          <button class="bg-white text-gray-800 font-bold rounded border-b-2 border-green-500 hover:border-green-600 hover:bg-green-500 hover:text-white shadow-md py-1 px-3 inline-flex items-center text-sm mt-4 js-submit" type="button">
            <span class="mr-2">Create post</span>
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
              <path fill="currentcolor" d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z"></path>
            </svg>
          </button>
        </div>
      </div>
    </div>
  </div>
{% endif %}

</div>
<script src="https://unpkg.com/aos@next/dist/aos.js"></script>
  <script>
    AOS.init();
  </script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="{% static 'js/main.js'%}"></script>
</body>
</html>

til/templates/includes/post.html
{% load thumbnail %}

<div class="max-w-4xl px-10 my-4 py-6 bg-white rounded-lg shadow-md" style='width: 50rem' data-aos="flip-down">
    <div class="flex justify-between items-center" >
        <span class="font-light text-gray-600">{{post.date|date:"F, j, Y, g:i a"}}</span>

    </div>
    <div class="mt-2">
        <p class="mt-2 text-gray-600">{{post.text}}</p>
    </div>
    <div class="flex justify-between items-center mt-4">
        {% if show_detail_link %}
            <a class="text-blue-600 hover:underline" href="{% url 'feed:detail' post.id %}" data-aos="zoom-out-left">Read more</a>
        {% else %}
            <span>&nbsp;</span>
        {% endif %}
        <div>
            <a class="flex items-center" href="{% url 'profiles:detail' post.author.username %}" data-aos="fade-down"
            data-aos-easing="linear"
            data-aos-duration="1500">

                {% thumbnail post.author.profile.image "373x373" crop="center" as im %}
                <img class="mx-4 w-10 h-10 object-cover rounded-full hidden sm:block" src="{{ im.url }}" alt="avatar">
                {% endthumbnail %}

                
                <h1 class="text-gray-700 font-bold">
            <!-- TODO Add a thumbnail and a link to the profile of the name of the author -->
                    
                    {{ post.author.username}}
                
                </h1>
            </a>
        </div>
    </div>
</div>